language: objective-c
matrix:
  include:
    - os: osx
      osx_image: xcode9.1
      env:
        - DEFAULT_SDK=iPhoneSimulator11.1.sdk
    - os: osx
      osx_image: xcode9
      env:
        - DEFAULT_SDK=iPhoneSimulator11.0.sdk
    - os: osx
      osx_image: xcode8.3
      env:
        - DEFAULT_SDK=iPhoneSimulator10.3.sdk
before_install:
# Download oclint
  - pod repo update
  - pod install
  - mkdir tmp
  - cd /tmp
  - curl -OL "https://github.com/oclint/oclint/releases/download/v0.13/oclint-0.13-x86_64-darwin-16.7.0.tar.gz"
  - tar -xvzf /tmp/oclint-0.13-x86_64-darwin-16.7.0.tar.gz
  - cd $TRAVIS_BUILD_DIR
  - ls

# Export oclint to path
  - OCLINT_HOME=/tmp/oclint-0.13
  - cp $OCLINT_HOME/bin/oclint* /usr/local/bin/
  - cp -rp $OCLINT_HOME/lib/* /usr/local/lib/
  - cp -rp $OCLINT_HOME/include/* /usr/local/include/

script:
  - set -o pipefail
  - oclint --version
  - oclint test.m --
  - xcodebuild -scheme SampleOCLint -workspace SampleOCLint.xcworkspace -configuration Debug -sdk iphonesimulator | tee xcodebuild.log | xcpretty -r json-compilation-database -o compile_commands.json
  - cat xcodebuild.log
  - cat compile_commands.json
  - cat /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/$DEFAULT_SDK/usr/include/module.modulemap
  - ls -al /usr/local/include/c++/v1/
  - ls -al /usr/local/lib/clang/5.0.0/include/
  - oclint-json-compilation-database -v -e Pods
  - cat ./sonar-reports/oclint.xml
